---
# install docker
- name: install docker
  when: 
  - "HTTP_SERVER is defined"
  environment:
    HTTP_SERVER: '{{ HTTP_SERVER }}'
  script: {{ item }}
  with_first_found:
    - files:
      - install-{{ ansible_distribution }}.sh  
      - install.sh