---
# install docker & rkt
- name: Run install-deps.sh
  environment:
    HTTP_SERVER: '{{ HTTP_SERVER }}'
  script: install-deps.sh

# register host name in /etc/hosts & ssh keys in root
- name: Run install-sys.sh
  environment:
    HOSTS_REGISTRY: '{{ HOSTS_REGISTRY }}'
    HOSTS_REGISTRY_IP: '{{ K8S_MASTER_HOST }}'
    HOSTS_ETCD: '{% for etcd_host in K8S_CLUSTER_ETCD %}{{ hostvars[etcd_host]['ansible_hostname']=hostvars[etcd_host]['ansible_default_ipv4']['address'] }}{% if loop.last %}{% else %},{% endif %}{% endfor %}'
    AUTHORIZED_KEYS: '{% for ssh_key in INSTALL_KEYS %}{{ SSH_KEYS[ssh_key] }}{% if loop.last %}{% else %},{% endif %}{% endfor %}'
  script: install-sys.sh  

- name: mkdir /etc/kubernetes/
  raw: mkdir -p /etc/kubernetes/downloads /etc/kubernetes/manifests /etc/kubernetes/scripts /etc/kubernetes/ssl 