---
# install docker & rkt
- name: Run install-deps.sh
  environment:
    HTTP_SERVER: '{{ HTTP_SERVER }}'
  script: install-deps.sh

# register host name in /etc/hosts & ssh keys in root
- name: Run install-sys.sh
  environment:
    HOSTS_REGISTRY: '{{ HOSTS_REGISTRY }}'
    HOSTS_REGISTRY_IP: '{{ K8S_MASTER_HOST }}'
    AUTHORIZED_KEYS: '{% for ssh_host in INSTALL_KEYS %}{{ SSH_KEYS[ssh_host] }}{% if loop.last %}{% else %},{% endif %}{% endfor %}'
  script: install-sys.sh  

- name: mkdir /etc/kubernetes/
  raw: mkdir -p /etc/kubernetes/downloads /etc/kubernetes/manifests /etc/kubernetes/scripts /etc/kubernetes/ssl 