---
# install docker & rkt
- name: Run install-deps.sh
  environment:
    HTTP_SERVER: '{{ HTTP_SERVER }}'
    YUM_SERVER: '{{ YUM_SERVER }}'
    YUM_RKT: '{{ YUM_RKT }}'
  script: install-deps.sh

# register host name in /etc/hosts & ssh keys in root
- name: Run install-sys.sh
  environment:
    REGISTRY_LOCAL_HOST: '{{ REGISTRY_LOCAL_HOST }}'
    REGISTRY_LOCAL_IP: '{{ K8S_MASTER_IP }}'
    AUTHORIZED_KEYS: '{% for ssh_host in INSTALL_KEYS %}{{ SSH_KEYS[ssh_host] }}{% if loop.last %}{% else %},{% endif %}{% endfor %}'
  script: install-sys.sh  

- name: mkdir /etc/kubernetes/
  raw: mkdir -p /etc/kubernetes/downloads /etc/kubernetes/manifests /etc/kubernetes/scripts /etc/kubernetes/ssl 