---
# install registry
- name: Run prepare.sh
  environment:
    HTTP_SERVER: '{{ HTTP_SERVER }}'
    RKT_ACI_REGISTRY: '{{ RKT_ACI_REGISTRY }}'
    RKT_ACI_REGISTRY_DATA: '{{ RKT_ACI_REGISTRY_DATA }}'
  script: prepare.sh
  when: K8S_CLUSTER[inventory_hostname] == "master"

- name: check need prepare.sh
  raw: stat /etc/kubernetes/scripts/prepare.sh
  register: need_scripts_prepare
  ignore_errors: True  
  when: K8S_CLUSTER[inventory_hostname] == "master"

- name: copy prepare.sh
  copy: src=prepare.sh dest=/etc/kubernetes/scripts/prepare.sh mode=0755
  when: K8S_CLUSTER[inventory_hostname] == "master" and need_scripts_prepare | failed  

- name: check need k8s-registry.service
  raw: stat /etc/systemd/system/k8s-registry.service
  register: need_services_registry
  ignore_errors: True  
  when: K8S_CLUSTER[inventory_hostname] == "master"

- name: template k8s-registry.service
  template: src=k8s-registry.service dest=/etc/systemd/system/k8s-registry.service mode=0644
  when: K8S_CLUSTER[inventory_hostname] == "master" and need_services_registry | failed

- name: start k8s-registry.service
  raw: systemctl daemon-reload && systemctl enable k8s-registry.service && systemctl start k8s-registry.service
  when: need_services_registry | failed