- name: check need /etc/kubernetes/scripts/etcd.sh
  raw: stat /etc/kubernetes/scripts/etcd.sh
  register: need_scripts_etcd
  ignore_errors: True  

- name: copy /etc/kubernetes/scripts/etcd.sh
  copy: src=etcd.sh dest=/etc/kubernetes/scripts/etcd.sh mode=0755
  when: need_scripts_etcd | failed

- name: check need etcd.service
  raw: stat /etc/systemd/system/etcd.service
  register: need_services_etcd
  ignore_errors: True  

- name: template etcd.service
  template: src=etcd.service dest=/etc/systemd/system/etcd.service mode=0644
  when: need_services_etcd | failed  

- name: start etcd.service
  raw: systemctl daemon-reload && systemctl enable etcd.service && systemctl start etcd.service
  when: need_services_etcd | failed   