- name: mkdir /etc/systemd/system/flannel-docker-opts.service.d
  raw: mkdir -p /etc/systemd/system/flannel-docker-opts.service.d && mkdir -p /etc/systemd/system/flanneld.service.d

- name: check need scripts/flanneld.sh
  raw: stat /etc/kubernetes/scripts/flanneld.sh
  register: need_scripts_flanneld
  ignore_errors: True  

- name: copy scripts/flanneld.sh
  copy: src=flanneld.sh dest=/etc/kubernetes/scripts/flanneld.sh mode=0755
  when: need_scripts_flanneld | failed  

- name: check need flannel-docker-opts.service.d/10-image.conf
  raw: stat /etc/systemd/system/flannel-docker-opts.service.d/10-image.conf
  register: need_services_flannel_opt_image
  ignore_errors: True  

- name: template flannel-docker-opts.service.d/10-image.conf
  template: src=flannel-docker-opts.service.d/10-image.conf dest=/etc/systemd/system/flannel-docker-opts.service.d/10-image.conf mode=0644
  when: need_services_flannel_opt_image | failed  

- name: check need flanneld.service.d/10-image.conf
  raw: stat /etc/systemd/system/flanneld.service.d/10-image.conf
  register: need_services_flannel_image
  ignore_errors: True  

- name: template flanneld.service.d/10-image.conf
  template: src=flanneld.service.d/10-image.conf dest=/etc/systemd/system/flanneld.service.d/10-image.conf mode=0644
  when: need_services_flannel_image | failed  

- name: check need flannel-docker-opts.service
  raw: stat /etc/systemd/system/flannel-docker-opts.service
  register: need_services_flannel_docker_opts
  ignore_errors: True  

- name: template flannel-docker-opts.service
  template: src=flannel-docker-opts.service dest=/etc/systemd/system/flannel-docker-opts.service mode=0644
  when: need_services_flannel_docker_opts | failed

- name: check need flanneld.service
  raw: stat /etc/systemd/system/flanneld.service
  register: need_services_flanneld
  ignore_errors: True  

- name: template flanneld.service
  template: src=flanneld.service dest=/etc/systemd/system/flanneld.service mode=0644
  when: need_services_flanneld | failed  

- name: start flanneld.service
  raw: systemctl daemon-reload && systemctl enable flanneld.service && systemctl start flanneld.service
  when: need_services_flanneld | failed    

- name: start flannel-docker-opts.service
  raw: systemctl daemon-reload && systemctl enable flannel-docker-opts.service && systemctl start flannel-docker-opts.service
  when: need_services_flannel_docker_opts | failed